import type { Node, Edge } from "@xyflow/react"

// Node states for strategic planning
export type NodeState =
  | "begin"
  | "draft"
  | "question"
  | "decision"
  | "doing"
  | "history"
  | "goal"

export const NODE_STATE_CONFIG: Record<
  NodeState,
  { label: string; color: string; bgClass: string; borderClass: string; iconName: string; opacity?: string }
> = {
  begin: {
    label: "Begin",
    color: "text-sky-700",
    bgClass: "bg-sky-50",
    borderClass: "border-sky-400",
    iconName: "play",
  },
  draft: {
    label: "Draft",
    color: "text-slate-500",
    bgClass: "bg-slate-50/70",
    borderClass: "border-slate-300",
    iconName: "file-edit",
    opacity: "opacity-70",
  },
  question: {
    label: "Question",
    color: "text-indigo-600",
    bgClass: "bg-indigo-50",
    borderClass: "border-indigo-400",
    iconName: "message-circle-question",
  },
  decision: {
    label: "Decision / Todo",
    color: "text-amber-700",
    bgClass: "bg-amber-50",
    borderClass: "border-amber-400",
    iconName: "help-circle",
  },
  doing: {
    label: "Doing / Action",
    color: "text-teal-700",
    bgClass: "bg-teal-50",
    borderClass: "border-teal-500",
    iconName: "zap",
  },
  history: {
    label: "History",
    color: "text-emerald-700",
    bgClass: "bg-emerald-50",
    borderClass: "border-emerald-400",
    iconName: "check-circle",
  },
  goal: {
    label: "Goal",
    color: "text-rose-700",
    bgClass: "bg-rose-50",
    borderClass: "border-rose-400",
    iconName: "target",
  },
}

export interface NodeComment {
  id: string
  userId: string
  userName: string
  text: string
  timestamp: string
}

export interface StrategicNodeData {
  title: string
  description: string
  state: NodeState
  comments: NodeComment[]
  assigneeId?: string
  isNextSmallGoal?: boolean
  attachedUsers?: string[]
  attachedLinks?: { label: string; url: string }[]
  /** Marks this node as generated by the intelligence system */
  isSystemGenerated?: boolean
  /** Marks this node as a 'ghost' suggestion that hasn't been committed yet */
  isGhost?: boolean
  /** Reference to the parent that spawned this ghost */
  ghostParentId?: string
  /** For question nodes: hint text shown to encourage drafting */
  questionHint?: string
  /** For blank/new nodes: search query for finding similar projects */
  searchQuery?: string
  /** Manually force show the 'Suggest next step' button even if node has work/assignee */
  forceSuggestionShow?: boolean
}

export type StrategicNode = Node<StrategicNodeData, "strategic">

export interface StrategicEdgeData {
  isPathTBD?: boolean
}

export type StrategicEdge = Edge<StrategicEdgeData>

export interface SwimLaneData {
  label: string
  orientation: "horizontal" | "vertical"
  color: string
  /** When true, the lane shows a forum-style comment thread view */
  showComments?: boolean
}

export type SwimLaneNode = Node<SwimLaneData, "swimlane">

export type CanvasNode = StrategicNode | SwimLaneNode

export type CanvasRole = "edit" | "comment" | "view"

export interface AppUser {
  id: string
  name: string
  email: string
  initials: string
  avatarColor: string
}

export interface CanvasProject {
  id: string
  name: string
  description: string
  createdAt: string
  members: { userId: string; role: CanvasRole }[]
  isTutorial?: boolean
}

export type SubscriptionType = "coordinator" | "contributor"

export interface AppNotification {
  id: string
  type: SubscriptionType
  title: string
  message: string
  timestamp: string
  read: boolean
}

export interface IntelligenceSuggestion {
  id: string
  text: string
  confidence: string
  category: string
}

export interface TrelloCardData {
  title: string
  list: string
  description: string
  checklist: { text: string; done: boolean }[]
  labels: { text: string; color: string }[]
  members: string[]
  dueDate: string
  activity: { user: string; text: string; time: string }[]
}
